In [197]:
import yfinance as yf
import numpy as np
import pandas as pd
import talib
import pandas_datareader.data as pdr
import statsmodels.api as sm
import datetime as dt
import matplotlib.pyplot as plt

In [198]:
end_date = dt.date(2021, 7, 1)
start_date = dt.date(2021, 3, 1)

In [199]:
data = pd.DataFrame()

In [200]:
data["AAPL"] = yf.Ticker("AAPL").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["MSFT"] = yf.Ticker("MSFT").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["GOOG"] = yf.Ticker("GOOG").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["GOOGL"] = yf.Ticker("GOOGL").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["AMZN"] = yf.Ticker("AMZN").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["FB"] = yf.Ticker("FB").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["TSLA"] = yf.Ticker("TSLA").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["NVDA"] = yf.Ticker("NVDA").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["ASML"] = yf.Ticker("ASML").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["PYPL"] = yf.Ticker("PYPL").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["ADBE"] = yf.Ticker("ADBE").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["CMCSA"] = yf.Ticker("CMCSA").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["CSCO"] = yf.Ticker("CSCO").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["NFLX"] = yf.Ticker("NFLX").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["PEP"] = yf.Ticker("PEP").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["INTC"] = yf.Ticker("INTC").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["COST"] = yf.Ticker("COST").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["AVGO"] = yf.Ticker("AVGO").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["AZN"] = yf.Ticker("AZN").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data["TXN"] = yf.Ticker("TXN").history(start = start_date, end = end_date, period = "1d")["Close"].pct_change().agg(lambda x: np.log(1+x))
data

,AAPL,MSFT,GOOG,GOOGL,AMZN,FB,TSLA,NVDA,ASML,PYPL,ADBE,CMCSA,CSCO,NFLX,PEP,INTC,COST,AVGO,AZN,TXN
Date,,,,,,,,,,,,,,,,,,,,
2021-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-02,-0.021115,-0.013042,-0.002728,-0.002506,-0.016540,-0.022562,-0.045549,-0.031968,-0.035602,-0.016359,-0.006366,-0.003680,-0.008749,-0.005134,0.003439,-0.026428,-0.010027,-0.018700,-0.007514,-0.015771
2021-03-03,-0.024761,-0.027352,-0.023952,-0.026042,-0.029358,-0.013958,-0.049635,-0.045905,-0.035315,-0.053919,-0.039654,-0.009631,-0.008605,-0.050773,-0.014835,-0.022124,-0.013918,-0.036991,-0.012014,-0.024894
2021-03-04,-0.015938,-0.003654,0.010982,0.011134,-0.009170,0.008693,-0.049844,-0.034522,-0.062823,-0.064742,-0.021161,0.003715,-0.012711,-0.018237,0.005550,-0.026560,-0.015180,-0.042956,0.001483,-0.043980
2021-03-05,0.010681,0.021252,0.028600,0.030571,0.007658,0.025446,-0.038532,0.007350,0.031886,-0.000084,0.004023,0.021281,0.037225,0.009925,0.032081,0.040486,-0.005406,0.014658,0.017421,0.028324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-24,-0.002171,0.005339,0.006467,0.003050,-0.015746,0.007576,0.034799,0.007749,0.019396,0.017512,0.006994,0.010400,0.000379,0.010322,0.005645,0.014552,0.000255,0.007259,0.007560,0.013397
2021-06-25,-0.002251,-0.006282,-0.002257,0.000069,-0.013903,-0.005288,-0.011763,-0.009127,-0.012728,-0.012388,0.002418,0.006401,0.005291,0.017242,0.005067,-0.002858,0.006204,-0.016863,0.015794,-0.002336
2021-06-28,0.012468,0.013865,-0.001383,0.000224,0.012397,0.040952,0.024770,0.048913,0.025751,0.013888,0.015645,-0.005688,-0.001886,0.011244,0.004294,0.027694,0.005132,0.022675,0.012058,0.017699
2021-06-29,0.011435,0.009924,-0.006336,-0.002153,0.001233,-0.010600,-0.011625,0.002087,-0.000611,-0.003035,0.003306,0.007813,-0.000945,0.000881,-0.000680,-0.012781,0.005658,0.009158,0.001830,0.007024
2021-06-30,0.004611,-0.001844,-0.005590,-0.001498,-0.002317,-0.011950,-0.001558,-0.001212,-0.018415,-0.004382,-0.008688,0.008454,0.001700,-0.009965,0.008336,-0.010807,-0.007854,-0.000650,-0.004664,-0.003012

In [201]:
data = data[1:]
data

,AAPL,MSFT,GOOG,GOOGL,AMZN,FB,TSLA,NVDA,ASML,PYPL,ADBE,CMCSA,CSCO,NFLX,PEP,INTC,COST,AVGO,AZN,TXN
Date,,,,,,,,,,,,,,,,,,,,
2021-03-02,-0.021115,-0.013042,-0.002728,-0.002506,-0.016540,-0.022562,-0.045549,-0.031968,-0.035602,-0.016359,-0.006366,-0.003680,-0.008749,-0.005134,0.003439,-0.026428,-0.010027,-0.018700,-0.007514,-0.015771
2021-03-03,-0.024761,-0.027352,-0.023952,-0.026042,-0.029358,-0.013958,-0.049635,-0.045905,-0.035315,-0.053919,-0.039654,-0.009631,-0.008605,-0.050773,-0.014835,-0.022124,-0.013918,-0.036991,-0.012014,-0.024894
2021-03-04,-0.015938,-0.003654,0.010982,0.011134,-0.009170,0.008693,-0.049844,-0.034522,-0.062823,-0.064742,-0.021161,0.003715,-0.012711,-0.018237,0.005550,-0.026560,-0.015180,-0.042956,0.001483,-0.043980
2021-03-05,0.010681,0.021252,0.028600,0.030571,0.007658,0.025446,-0.038532,0.007350,0.031886,-0.000084,0.004023,0.021281,0.037225,0.009925,0.032081,0.040486,-0.005406,0.014658,0.017421,0.028324
2021-03-08,-0.042567,-0.018345,-0.040836,-0.043651,-0.016300,-0.034531,-0.060228,-0.072221,-0.048298,-0.055740,-0.045551,0.007054,0.026879,-0.045684,-0.006788,-0.014761,-0.018768,-0.066332,0.002701,-0.035332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-24,-0.002171,0.005339,0.006467,0.003050,-0.015746,0.007576,0.034799,0.007749,0.019396,0.017512,0.006994,0.010400,0.000379,0.010322,0.005645,0.014552,0.000255,0.007259,0.007560,0.013397
2021-06-25,-0.002251,-0.006282,-0.002257,0.000069,-0.013903,-0.005288,-0.011763,-0.009127,-0.012728,-0.012388,0.002418,0.006401,0.005291,0.017242,0.005067,-0.002858,0.006204,-0.016863,0.015794,-0.002336
2021-06-28,0.012468,0.013865,-0.001383,0.000224,0.012397,0.040952,0.024770,0.048913,0.025751,0.013888,0.015645,-0.005688,-0.001886,0.011244,0.004294,0.027694,0.005132,0.022675,0.012058,0.017699
2021-06-29,0.011435,0.009924,-0.006336,-0.002153,0.001233,-0.010600,-0.011625,0.002087,-0.000611,-0.003035,0.003306,0.007813,-0.000945,0.000881,-0.000680,-0.012781,0.005658,0.009158,0.001830,0.007024
2021-06-30,0.004611,-0.001844,-0.005590,-0.001498,-0.002317,-0.011950,-0.001558,-0.001212,-0.018415,-0.004382,-0.008688,0.008454,0.001700,-0.009965,0.008336,-0.010807,-0.007854,-0.000650,-0.004664,-0.003012

In [202]:
correlation = data.corr()
correlation = np.abs(correlation)
correlation["Stock 1"] = correlation.index
correlation = correlation.melt(id_vars = "Stock 1", var_name = "Stock 2", value_name = "Abs Corr")
correlation = correlation[correlation["Stock 1"] < correlation["Stock 2"]].dropna()
correlation = correlation.sort_values("Abs Corr", ascending = True)
correlation

    Stock 1 Stock 2  Abs Corr
278     AZN    NFLX  0.030713
118     AZN      FB  0.033575
58      AZN    GOOG  0.034702
134     PEP    TSLA  0.039626
78      AZN   GOOGL  0.045773
..      ...     ...       ...
187    NVDA    PYPL  0.818822
190    ADBE    PYPL  0.841470
388    ASML     TXN  0.846943
397    AVGO     TXN  0.859520
62     GOOG   GOOGL  0.979623

[190 rows x 3 columns]

In [203]:
data["AZN + GOOG"] = data["GOOG"] + data["AZN"]
data = data.drop(columns = ["AZN", "GOOG"])
data

C:\Users\shyam\AppData\Local\Temp/ipykernel_17280/4099056121.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["AZN + GOOG"] = data["GOOG"] + data["AZN"]

,AAPL,MSFT,GOOGL,AMZN,FB,TSLA,NVDA,ASML,PYPL,ADBE,CMCSA,CSCO,NFLX,PEP,INTC,COST,AVGO,TXN,AZN + GOOG
Date,,,,,,,,,,,,,,,,,,,
2021-03-02,-0.021115,-0.013042,-0.002506,-0.016540,-0.022562,-0.045549,-0.031968,-0.035602,-0.016359,-0.006366,-0.003680,-0.008749,-0.005134,0.003439,-0.026428,-0.010027,-0.018700,-0.015771,-0.010242
2021-03-03,-0.024761,-0.027352,-0.026042,-0.029358,-0.013958,-0.049635,-0.045905,-0.035315,-0.053919,-0.039654,-0.009631,-0.008605,-0.050773,-0.014835,-0.022124,-0.013918,-0.036991,-0.024894,-0.035966
2021-03-04,-0.015938,-0.003654,0.011134,-0.009170,0.008693,-0.049844,-0.034522,-0.062823,-0.064742,-0.021161,0.003715,-0.012711,-0.018237,0.005550,-0.026560,-0.015180,-0.042956,-0.043980,0.012465
2021-03-05,0.010681,0.021252,0.030571,0.007658,0.025446,-0.038532,0.007350,0.031886,-0.000084,0.004023,0.021281,0.037225,0.009925,0.032081,0.040486,-0.005406,0.014658,0.028324,0.046021
2021-03-08,-0.042567,-0.018345,-0.043651,-0.016300,-0.034531,-0.060228,-0.072221,-0.048298,-0.055740,-0.045551,0.007054,0.026879,-0.045684,-0.006788,-0.014761,-0.018768,-0.066332,-0.035332,-0.038135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-24,-0.002171,0.005339,0.003050,-0.015746,0.007576,0.034799,0.007749,0.019396,0.017512,0.006994,0.010400,0.000379,0.010322,0.005645,0.014552,0.000255,0.007259,0.013397,0.014027
2021-06-25,-0.002251,-0.006282,0.000069,-0.013903,-0.005288,-0.011763,-0.009127,-0.012728,-0.012388,0.002418,0.006401,0.005291,0.017242,0.005067,-0.002858,0.006204,-0.016863,-0.002336,0.013536
2021-06-28,0.012468,0.013865,0.000224,0.012397,0.040952,0.024770,0.048913,0.025751,0.013888,0.015645,-0.005688,-0.001886,0.011244,0.004294,0.027694,0.005132,0.022675,0.017699,0.010676
2021-06-29,0.011435,0.009924,-0.002153,0.001233,-0.010600,-0.011625,0.002087,-0.000611,-0.003035,0.003306,0.007813,-0.000945,0.000881,-0.000680,-0.012781,0.005658,0.009158,0.007024,-0.004506
2021-06-30,0.004611,-0.001844,-0.001498,-0.002317,-0.011950,-0.001558,-0.001212,-0.018415,-0.004382,-0.008688,0.008454,0.001700,-0.009965,0.008336,-0.010807,-0.007854,-0.000650,-0.003012,-0.010254

In [205]:
correlation = data.corr()
correlation = np.abs(correlation)
correlation["Stock 1"] = correlation.index
correlation = correlation.melt(id_vars = "Stock 1", var_name = "Stock 2", value_name = "Abs Corr")
correlation = correlation[correlation["Stock 1"] < correlation["Stock 2"]].dropna()
correlation = correlation.sort_values("Abs Corr", ascending = True)
correlation

    Stock 1 Stock 2  Abs Corr
108     PEP    TSLA  0.039626
106    CSCO    TSLA  0.077542
193    AMZN   CMCSA  0.131118
165     PEP    PYPL  0.143631
105   CMCSA    TSLA  0.146546
..      ...     ...       ...
19     AAPL    MSFT  0.796642
158    NVDA    PYPL  0.818822
161    ADBE    PYPL  0.841470
330    ASML     TXN  0.846943
339    AVGO     TXN  0.859520

[171 rows x 3 columns]

In [206]:
data["PEP + TSLA"] = data["TSLA"] + data["PEP"]
data = data.drop(columns = ["TSLA", "PEP"])
data

,AAPL,MSFT,GOOGL,AMZN,FB,NVDA,ASML,PYPL,ADBE,CMCSA,CSCO,NFLX,INTC,COST,AVGO,TXN,AZN + GOOG,PEP + TSLA
Date,,,,,,,,,,,,,,,,,,
2021-03-02,-0.021115,-0.013042,-0.002506,-0.016540,-0.022562,-0.031968,-0.035602,-0.016359,-0.006366,-0.003680,-0.008749,-0.005134,-0.026428,-0.010027,-0.018700,-0.015771,-0.010242,-0.042110
2021-03-03,-0.024761,-0.027352,-0.026042,-0.029358,-0.013958,-0.045905,-0.035315,-0.053919,-0.039654,-0.009631,-0.008605,-0.050773,-0.022124,-0.013918,-0.036991,-0.024894,-0.035966,-0.064470
2021-03-04,-0.015938,-0.003654,0.011134,-0.009170,0.008693,-0.034522,-0.062823,-0.064742,-0.021161,0.003715,-0.012711,-0.018237,-0.026560,-0.015180,-0.042956,-0.043980,0.012465,-0.044294
2021-03-05,0.010681,0.021252,0.030571,0.007658,0.025446,0.007350,0.031886,-0.000084,0.004023,0.021281,0.037225,0.009925,0.040486,-0.005406,0.014658,0.028324,0.046021,-0.006451
2021-03-08,-0.042567,-0.018345,-0.043651,-0.016300,-0.034531,-0.072221,-0.048298,-0.055740,-0.045551,0.007054,0.026879,-0.045684,-0.014761,-0.018768,-0.066332,-0.035332,-0.038135,-0.067016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-24,-0.002171,0.005339,0.003050,-0.015746,0.007576,0.007749,0.019396,0.017512,0.006994,0.010400,0.000379,0.010322,0.014552,0.000255,0.007259,0.013397,0.014027,0.040444
2021-06-25,-0.002251,-0.006282,0.000069,-0.013903,-0.005288,-0.009127,-0.012728,-0.012388,0.002418,0.006401,0.005291,0.017242,-0.002858,0.006204,-0.016863,-0.002336,0.013536,-0.006696
2021-06-28,0.012468,0.013865,0.000224,0.012397,0.040952,0.048913,0.025751,0.013888,0.015645,-0.005688,-0.001886,0.011244,0.027694,0.005132,0.022675,0.017699,0.010676,0.029064
2021-06-29,0.011435,0.009924,-0.002153,0.001233,-0.010600,0.002087,-0.000611,-0.003035,0.003306,0.007813,-0.000945,0.000881,-0.012781,0.005658,0.009158,0.007024,-0.004506,-0.012305
2021-06-30,0.004611,-0.001844,-0.001498,-0.002317,-0.011950,-0.001212,-0.018415,-0.004382,-0.008688,0.008454,0.001700,-0.009965,-0.010807,-0.007854,-0.000650,-0.003012,-0.010254,0.006778

In [207]:
correlation = data.corr()
correlation = np.abs(correlation)
correlation["Stock 1"] = correlation.index
correlation = correlation.melt(id_vars = "Stock 1", var_name = "Stock 2", value_name = "Abs Corr")
correlation = correlation[correlation["Stock 1"] < correlation["Stock 2"]].dropna()
correlation = correlation.sort_values("Abs Corr", ascending = True)
correlation

    Stock 1 Stock 2  Abs Corr
165    AMZN   CMCSA  0.131118
208    CSCO    NFLX  0.151555
135   CMCSA    PYPL  0.157900
207   CMCSA    NFLX  0.170119
170    ADBE   CMCSA  0.210177
..      ...     ...       ...
18     AAPL    MSFT  0.796642
131    NVDA    PYPL  0.818822
134    ADBE    PYPL  0.841470
276    ASML     TXN  0.846943
284    AVGO     TXN  0.859520

[153 rows x 3 columns]